# Automated cleanup script generated by AI
# Deletes non-essential test / diagnostic / analysis / setup helper files
# Run from repository root

$ErrorActionPreference = 'SilentlyContinue'

$patterns = @(
  'test-*.js','test-*.cjs','test-*.ts','test-*.ps1','test-*.sh','test-*.html',
  '*test*.html','*test*.ps1','*test*.cjs','*test*.js',
  'audit-*.js','AUDIT_*',
  'final-*.js','FINAL_STATUS*','final-summary-crud.*','final-import-report.*',
  'validation-*.js','validation-*.ps1','VALIDATION_*','validation-finale.*','validation-simple.ps1','validation-complete.ps1',
  'validate-*.ps1','validate-*.js',
  'verify-*.js','verify-*.ps1','verifier-*.js',
  'implement-*.js','import-*.js','import-*.cjs','import-*.ts','integrate-json-data.ps1',
  'activate-*.js','activate-*.cjs',
  'quick-*.ps1','quick-*.js',
  'diagnose-*.js','check-*.js','find-*.js','generate-*.ps1','generate-*.bat','generate_usecase*','generate-password-hashes.*',
  'create-test-users.*','create-admin-user.*',
  'start-housy*','start-server*','START_HOUSY*',
  'ANALYSE_*','EXPLICATION_*','OLLAMA_*','PROMPT_ARCHITECTURE*',
  'CRUD_FEATURES_TEST_REPORT.json','CRUD_IMPLEMENTATION_PLAN.json','REAL_DATABASE_VERIFICATION_SUMMARY.js',
  'plantuml.jar','payments_confirmer_le_paiement_implementation.tsx'
)

$all = @{}
foreach($pat in $patterns){
  Get-ChildItem -Recurse -File -Include $pat -ErrorAction SilentlyContinue | ForEach-Object {
    if(-not $all.ContainsKey($_.FullName)) { $all[$_.FullName] = $_ }
  }
}

$log = 'deletion-log.txt'
"Cleanup run $(Get-Date -Format o)" | Out-File $log -Encoding utf8
$all.Keys | Sort-Object | ForEach-Object { $_ | Out-File $log -Append }

Write-Host ("Identified {0} files" -f $all.Count)

# Delete
$all.Values | ForEach-Object { Remove-Item $_.FullName -Force }
Write-Host 'Deletion complete.'
